[project]
name = "aiomqttc"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "rich>=14.0.0",
]

[tool.setuptools]
py-modules = ["aiomqttc", "main", "wifi", "config"]